framework:
    assets:
        packages:
            front:
                json_manifest_path: '%kernel.project_dir%/public/front/build/manifest.json'
            admin:
                json_manifest_path: '%kernel.project_dir%/public/admin/build/manifest.json'
