version: "3.1"

services:
    php-test:
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - .:/var/www:delegated
        links:
            - db-test
        networks:
            tic-tac-toc_test:
    db-test:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: tic-tac-toc_test
        ports:
            - 3307:3306
        networks:
            tic-tac-toc_test:
networks:
    tic-tac-toc_test:
