version: "3.1"

services:
    web:
        container_name: web
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - .:/var/www:delegated
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: php
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - .:/var/www:delegated
    node:
        container_name: node
        build:
            context: ./docker/node
        command: yarn run dev-server
        working_dir: /usr/src/app
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            - NODE_ENV=development
        volumes:
            - .:/usr/src/app:cached
        ports:
            - 8080:8080
